### PR TITLE
Infinite animation on the body to solve the general/adjacent sibling sel...

### PR DESCRIPTION
**Pull request by technopagan**
Infinite animation on the body to solve the general/adjacent sibling selector bug #45168 in WebKit (Android <= 4.1.2) causes high CPU/GPU load due to the rendering engine reflow calculations as mentioned in http://css-tricks.com/webkit-sibling-bug/ . Wrapping the label and the menu within a div enables us to use a selector chain that does not require any animation and still works across all browsers. This does not cause reflows / layout thrashing and has been successfully tested. Thanks to http://stackoverflow.com/a/14201802 for the input on how to fix it.

### CODE REVIEW

**Comment by micjamking** [comment]
Do we need the added specificity of the wrapping `div` in the CSS selector? It seems a bit verbose...

Overall, this seems like a pretty solid fix; I'd always prefer a legitimate enhancement over a hack :wink:  

Has this been tested on Android <= 4.1.2?

**Comment by technopagan** [comment]
Hi Mike!

While the wrapping div selector is verbose, it does seem to be necessary to work around the WebKit bug. Compared to the layout thrashing / GPU load caused by the constant animation on the body, it is the lesser of two evils.

We (developers using Navigataur as a base for a live site's menu) have tested this new code on Android <= 4.1.2 (both real devices as well as Android emulator) and various other browsers such as Chrome, Firefox and even IE8 (using a 2nd Navigataur instance which is on buttonized state for IE8 on desktop). So it seems quite safe.

**Comment by coogie** [comment]
How about using a `nav` tag as a wrapper instead of a div? It would add the required wrapping element and also add a semantic level to the code.

**Comment by micjamking** [comment]
Ignore my previous statement about the `div` requirement in the CSS selector, it makes perfect sense when I look at your changes again. 

I definitely prefer the added semantics of using a `nav` over a `div` element, but along with that we should recommend setting `role="navigation"` for screen-readers as well.

I'll make the changes in the README after I merge.

Thanks for all of your help and input folks!

**Pull request merged**
